name: Main

on:
  push:
    branches: [ master ]

jobs:
  csharp:
    name: C#
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Generate nuget
        run: |
          dotnet test ./ISO3166.UnitTests
          cd ./ISO3166.Generator/
          dotnet run -c Release
          cd ..
          rm ./ISO3166/Country.cs
          cp ./ISO3166.Generator/Output/Country.cs ./ISO3166/Country.cs
          dotnet pack -c Release ./ISO3166 --output ./artifact

      - name: Push to nuget
        run: |
          cd ./artifact
          dotnet nuget push "*.nupkg" -s https://api.nuget.org/v3/index.json -k ${{ secrets.NUGET_API_KEY }} --skip-duplicate
