name: Main

on:
  push:
    branches: [ main ]

jobs:
  csharp:
    name: C#
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Generate nuget
        run: |
          cd ./ISO3166.Generator/
          dotnet run -c Release

      - name: Run tests
        run: |
          cd ..
          dotnet test ./ISO3166.Generator/Output/CSharp/ISO3166.UnitTests

      - name: Push to nuget
        run: |
          cd ..
          dotnet pack -c Release ./ISO3166.Generator/Output/CSharp/ISO3166 --output ./artifact
          cd ./artifact
          dotnet nuget push "*.nupkg" -s https://api.nuget.org/v3/index.json -k ${{ secrets.NUGET_API_KEY }} --skip-duplicate
